### ISSUE TITLE
Unclaimed slayer rewards

### ISSUE THREAD

**Issue by TheDGOfficial** [LeaPhant/skyblock-stats#84] opened 2021-07-11 01:41 UTC
I know this project is discontinued, so there will be no new features etc, but the site is online still and repo is not archived so I guess bugs will be fixed? There is a bug where it says unclaimed slayer rewards on revenant slayer even though I claimed them, checked them, and did some more revs to make sure it is not related to the XP.

I'm currently Rev 8. Mostly got it from T4s, only did T5s when RNGesus meter come close. IHave like 7 T5 kills. Maybe the bug is caused by T5 not accounting or such, but the tier list shows T5 kill count correct.

Profile link:
https://sky.lea.moe/stats/TheDark_Gamer/Orange

This can be closed, since this bug doesn't happen on SkyCrypt, but I'd like to have this fixed as well here. I checked the source code but I'm not a web guy, so can't fix and make a PR myself here.

**Comment by LeaPhant** [comment] 2021-07-11 11:16
Fixed in https://github.com/LeaPhant/skyblock-stats/commit/888ccb4f2366d4a3d10c54df4f1da49511f25b2d. The bug was caused by this field having an unexcepted format (probably since the tier 5 update):

![image](https://user-images.githubusercontent.com/14080165/125192867-27e97280-e24a-11eb-8c3e-e887a1d21ca7.png)

**Closed by LeaPhant** 2021-07-11 11:16 UTC
